import streamlit as st
st.markdown('<h1 style="color:yellow;">HI!!</h1>', unsafe_allow_html=True)
st.markdown('<h1 style="color:yellow;">IT IS KEERTHANA!</h1>', unsafe_allow_html=True)
st.markdown('<h2 style="color:violet;">Designation</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">Student</h3>', unsafe_allow_html=True)
st.markdown('<h2 style="color:violet;">Institute</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">KGISL Institite of Technology</h3>', unsafe_allow_html=True)
st.markdown('<h2 style="color:violet;">course</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:orange;">B.Tech Artificial Intelligence and Data Scince</h3>', unsafe_allow_html=True)
st.image("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyyHWRRZ7r0Z4Ygl13ygkSsmKXooxG3rpJng&s")
st.write("Artificial intelligence (AI) and data science are closely intertwined fields that are transforming industries across the globe. AI focuses on creating systems capable of performing tasks that typically require human intelligence, such as understanding language, recognizing patterns, and making decisions. Data science, on the other hand, involves extracting insights and knowledge from vast amounts of data through techniques like machine learning, statistical analysis, and data visualization. Together, these fields enable organizations to harness the power of big data, automate processes, and develop intelligent systems that can improve decision-making, enhance customer experiences, and drive innovation. As AI models become more advanced and data science techniques evolve, their combined impact continues to reshape the way we live, work, and interact with technology.")
st.markdown('<h2 style="color:violet;">SKILLS</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">* good at c,c++,python language</h3>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">* front end developer in python</h3>', unsafe_allow_html=True)
st.image("https://www.shutterstock.com/image-photo/python-highlevel-programing-language-application-260nw-1402830182.jpg")
st.markdown('<h3 style="color:white;">* good problem solving skills</h3>', unsafe_allow_html=True)
st.markdown('<h2 style="color:violet;>"INTERESTED</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">* Machine learning</h3>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">* java script</h3>', unsafe_allow_html=True)
st.markdown('<h2 style="color:violet;">PROJECTS</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:orange;">Number guessing game</h3>', unsafe_allow_html=True)
st.image("https://content.instructables.com/FKF/3M2G/K1NVASKL/FKF3M2GK1NVASKL.jpg?auto=webp&frame=1&width=320&md=MjAxOS0xMC0xNCAwNzo0MDo1OC4w")
st.write("REPOSITOIRY LINK:https://github.com/Keerthana-saravana/python_games.git")
st.markdown('<h2 style="color:violet;">CONCLUSION</h2>', unsafe_allow_html=True)
st.markdown('<h3 style="color:white;">"This is all about me!!"</h3>', unsafe_allow_html=True)
